### ISSUE TITLE
API bans

### ISSUE THREAD

**Issue by Jonybat** [adameste/anidbcli#10]
Hi

Did you ever had issues with API bans?

I seem to get it after executing `anidbcli api -u user -p pass -k key -sr '%a_romaji% - ep%ep_no% - %ep_english% - [%g_name%]' 'file'` 5 or so times in a row.

**Comment by msdos** [comment]
I've had some problems with API bans, but they are temporary, like 30 minutes or so. When that happens, I stop running anidbcli.

Don't know if this package could be improved to avoid this or if this problem is normal.

> Flooding and Caching
> All users of this API should employ heavy local caching. Requesting the same dataset multiple times on a single day can get you banned. The same goes for request flooding. You should not request more than one page every two seconds.

https://wiki.anidb.net/w/HTTP_API_Definition

**Comment by Jonybat** [comment]
I thought about that and I've read that page before, so I tried adding a 5s sleep after line 77 of the anidbconnector.py file, but got the same result. I don't understand most of what requests are being made, and I'm not really confortable with python, so I guess I'll wait for some expert xD

**Comment by XVicarious** [comment]
Honestly until something changes with how the website is managed, its something that you'll have to put up with. They define some numbers but then have completely arbitrary restrictions in other places. They say "use common sense", but common sense isn't as universal as one might think, or it could just be common sense for the year 2008.

**Comment by purposelycryptic** [comment]
@Jonybat - AniDB's Flood Control kicks in after 5 requests, so it sounds like the delays between requests are set too short. The official API definition calls for no more than one request every 2 seconds short term, and one request every 4 seconds long-term, with the switchover from short- to long-term rate-limiting occurring after an intentionally undisclosed amount of time.

If it helps, I've used these timings for Shoko, and it dramatically dropped my ban-rate (down to something like 4-5 bans while processing 30k+ files):

> 3000ms short terms delay, 5000ms long term delay, with a switchover to long term delay after 30 minutes of activity, and return to short term delay after 45 minutes of inactivity.

It's a second longer than the official API definition, but I was getting frequent, massive bans using 2500ms STD, 4500ms LTD, so that extra half-second seems worth it.

**Comment by Jonybat** [comment]
> @Jonybat - AniDB's Flood Control kicks in after 5 requests, so it sounds like the delays between requests are set too short. The official API definition calls for no more than one request every 2 seconds short term, and one request every 4 seconds long-term, with the switchover from short- to long-term rate-limiting occurring after an intentionally undisclosed amount of time.
> 
> If it helps, I've used these timings for Shoko, and it dramatically dropped my ban-rate (down to something like 4-5 bans while processing 30k+ files):
> 
> > 3000ms short terms delay, 5000ms long term delay, with a switchover to long term delay after 30 minutes of activity, and return to short term delay after 45 minutes of inactivity.
> 
> It's a second longer than the official API definition, but I was getting frequent, massive bans using 2500ms STD, 4500ms LTD, so that extra half-second seems worth it.

I must be missing something. I just tried with 30 seconds between execution (as in first post) and got banned on the 7th time...

**Comment by purposelycryptic** [comment]
>I must be missing something. I just tried with 30 seconds between execution (as in first post) and got banned on the 7th time...

Being banned on the 7th time makes sense, since the first 5 are ignored, so, assuming the interval is too short, the ban would start after the second connection after that (7th total).

But, seeing as you specifically set the connection interval to be far greater than required by the API, there is obviously something more to it. 

Do you have anything else communicating with AniDB in any way at the same time? Not just the UPD API, but the HTTP API, the TCP API (which I think only AOM and maybe AVDump2 get to use?), or even browsing the site (that definitely got me banned once, though I don't think it was supposed to)?

If not, then all I can think of is that AnidbCLI is sending additional requests not affected by the 30-second delay you implemented; if you are manually running single requests with 30 seconds between each, then I really have no clue, unless AnidbCLI is requesting each tag-variable individually for the ed2k hash of your file, rather than caching the complete info from a single request and pulling the data from that. Since AniDB's APIs have pretty strict rate limits, it kind of requires the use of lots of local caching (also *strongly* encouraged by the admins). But it seems like other users would have run into the same problem if that was really the issue:-/

I haven't had a chance to really look at the code in detail yet (I'm pretty sick at the moment, been bed-bound for going on 3 months now, some kind of interstitial lung disease that the doctors haven't been able to figure out so far, so my ability to focus and actually do stuff other than be a zombie comes and goes somewhat randomly), so I don't really know enough atm to figure out exactly what is going on.

I'll definitely try and look into it though - hopefully someone more knowledgeable/less sick will be able to help first, since, well, I sadly tend to be a little slow these days, but if not, I'm sure we'll figure something out :-)

**Comment by adameste** [comment]
Well,

The bans are in the API specification, after x logins in a row you get banned. This really simplifies the developement process... IDK how the bans are set, but after about 5 logins you get banned for like 30 minutes.

Use case for my program is to have "unsorted folder" and a batch script, that sorts all the files inside it to corresponding folder and a second one, that adds them to mylist & adds them to "wached" folder. So i run it once or twice per day at most, so the bans don't present a problem for me.

To the discussion. Using HTTP/TCP API is not possible, as it is provided only to some programs, the UDP api is the only one somewhat "public". And so the bans are inevitable. This project was made as a school project, only to meet the requirements, but it is somehow really getting used.

I have a solution in mind, but it could be quite a pain in the neck to use it, if you invoke the script more times in a row:

SOLUTION: Implement 2 new launch options
 - export login info from file **-o**
 - import login info from file **-i**

I will save the api token to a file and will not log out at the end of the program and write the neccesary session info into a file. This file could be imported by the next launch of the program, so there will be no login process that could result in bans. However it would take a bit of time to implement and test this, so I need to know, if it would help Your use case :)

**Comment by adameste** [comment]
But the easiest solution remains to do all the neccessary work in one command. You can pass multiple files/folders to anidbcli in one call.

**Comment by Jonybat** [comment]
> > I must be missing something. I just tried with 30 seconds between execution (as in first post) and got banned on the 7th time...
> 
> Being banned on the 7th time makes sense, since the first 5 are ignored, so, assuming the interval is too short, the ban would start after the second connection after that (7th total).
> 
> But, seeing as you specifically set the connection interval to be far greater than required by the API, there is obviously something more to it.
> 
> Do you have anything else communicating with AniDB in any way at the same time? Not just the UPD API, but the HTTP API, the TCP API (which I think only AOM and maybe AVDump2 get to use?), or even browsing the site (that definitely got me banned once, though I don't think it was supposed to)?

I didn't think of that. I had the aniDB metadata Kodi plugin, which i just disabled. Its not using my login credentials, but it is coming from the same IP, so it could be the issue here. I'll try again tomorow  or so to see if i still get banned.

> If not, then all I can think of is that AnidbCLI is sending additional requests not affected by the 30-second delay you implemented; if you are manually running single requests with 30 seconds between each, then I really have no clue, unless AnidbCLI is requesting each tag-variable individually for the ed2k hash of your file, rather than caching the complete info from a single request and pulling the data from that. Since AniDB's APIs have pretty strict rate limits, it kind of requires the use of lots of local caching (also _strongly_ encouraged by the admins). But it seems like other users would have run into the same problem if that was really the issue:-/

I'm not running them manually, but its just like as if it was. I basically have a bash script that iterates over filenames on a file and processes them individually with anidbcli. I added a ``sleep 30`` after each anidbcli invocation. 

> I haven't had a chance to really look at the code in detail yet (I'm pretty sick at the moment, been bed-bound for going on 3 months now, some kind of interstitial lung disease that the doctors haven't been able to figure out so far, so my ability to focus and actually do stuff other than be a zombie comes and goes somewhat randomly), so I don't really know enough atm to figure out exactly what is going on.
> 
> I'll definitely try and look into it though - hopefully someone more knowledgeable/less sick will be able to help first, since, well, I sadly tend to be a little slow these days, but if not, I'm sure we'll figure something out :-)

Thanks for the effort. Feel better :)

> Well,
> 
> The bans are in the API specification, after x logins in a row you get banned. This really simplifies the developement process... IDK how the bans are set, but after about 5 logins you get banned for like 30 minutes.

Ah...That makes more sense according to my experience. They only mention data requests, and unless anidbcli is doing more than one request every time it is executed, I am sure that I'm never hitting the limits that they disclose. Now if the bans are by number of logins over an undetermined period of time, it will most likely trigger.

> Use case for my program is to have "unsorted folder" and a batch script, that sorts all the files inside it to corresponding folder and a second one, that adds them to mylist & adds them to "wached" folder. So i run it once or twice per day at most, so the bans don't present a problem for me.

I need it in a slightly different way, because i want the "un-renamed" files in their respective folders, even if their name is not 100% accurate with aniDB. Those filenames are added to a file that is then processed by the script that calls anidbcli. This is the one in case you are interested: https://github.com/Jonybat/bash_scripts/blob/master/anime_renamer.sh

> To the discussion. Using HTTP/TCP API is not possible, as it is provided only to some programs, the UDP api is the only one somewhat "public". And so the bans are inevitable. This project was made as a school project, only to meet the requirements, but it is somehow really getting used.

I am aware of that. Thank you for this, it is quite good and useful, despite aniDB limitations.

> I have a solution in mind, but it could be quite a pain in the neck to use it, if you invoke the script more times in a row:
> 
> SOLUTION: Implement 2 new launch options
> 
>     * export login info from file **-o**
> 
>     * import login info from file **-i**
> 
> 
> I will save the api token to a file and will not log out at the end of the program and write the neccesary session info into a file. This file could be imported by the next launch of the program, so there will be no login process that could result in bans. However it would take a bit of time to implement and test this, so I need to know, if it would help Your use case :)

If the number of logins is whats triggering the bans, that would probably fix it then. I'll let you know by the end of the week or so, once I'm sure nothing else is using aniDB from the same IP.

> But the easiest solution remains to do all the neccessary work in one command. You can pass multiple files/folders to anidbcli in one call.

That would be a big change in the current work flow of the script, but if it comes to that and that does work around the issue, I'll figure it out.

**Comment by purposelycryptic** [comment]
RE:
> To the discussion. Using HTTP/TCP API is not possible, as it is provided only to some programs, the UDP api is the only one somewhat "public". And so the bans are inevitable. This project was made as a school project, only to meet the requirements, but it is somehow really getting used.

The HTTP API is public, but is useless for the purposes of this project - its main use is to access series metadata in XML form and similar data, rather than interacting with the database. The TCP API is completely closed-source.

Had no idea this started as a school project, btw :-)

For a better idea of how to work with the UDP API, I'd recommend checking out the AniAdd's code - the code for the latest version seems to have dropped off the face of the earth, but the API interactions are largely the same in [this older fork](https://github.com/xyzz/aniAdd), and are well-commented; it's in Java, but the basics are easy enough to read.

FYI, I believe the UDP connection needs at least one call per minute to keep the session active, otherwise it disconnects you, but a simple stay-alive signal is all it requires. Ideally, it is used to sign in, send out your calls at regular, not-too-fast intervals, receive your responses, then log out/let the connection time out when you're done. 

It sounds like the bash script @Jonybat has been using has unintentionally been opening a new connection before the old one timed out, which the API probably sees as repeated attempts to open multiple simultaneous sessions with the same account from the same IP, which definitely is the sort of thing that will get you banned. Since none of the calls are otherwise part of the same session, the usual rate-limiting shouldn't be taking place (since those are triggered through flooding _during_ a session, vs flooding _with_ sessions), so that seems like the most likely culprit.

My own usage case is somewhat different than either of yours, in that I plan to run AnidbCLI as the second step in a batch file triggered when new releases are downloaded based on an RSS feed - first step runs AVDump2, adding the file to AniDB, after which AnidbCLI adds them to my MyList. Since I rarely have multiple individual releases downloading within a minute of each other, log-in flooding shouldn't be an issue, although, since I do use HAMA, an AniDB metadata agent, in Plex, I guess I'll find out whether AniDB bans you for separate calls on each of the APIs within a short period (AVDump2 uses TCP, AnidbCLI uses UDP, HAMA uses HTML...). Pretty sure the TCP API isn't subject to rate limiting at all, because only two programs can access it, and both are closed-source releases from AniDB, but the other two are a different story... Probably fine unless I happen to get multiple releases simultaneously by coincidence *crosses fingers*.

**Comment by Jonybat** [comment]
Meanwhile I confirmed that renaming multiple files in one command invocation works, so the bans do seem to be related to the logins indeed.

**Comment by adameste** [comment]
Well, I looked at the API specification again. The session times out after **35 minutes** of not using it, so it's plenty of time. I can save the session info to a file (along with a timestamp) instead of properly logging out and reusing the session data if possible (now - timestamp < 35 minutes). The simplest approach (and the hardest one to implement) is to create new **-p --persistent** parameter, that you could simply add to invocations in your script and it should work without any problems.
The con is, that i will have to create a file on your filesystem to store this data in following directories:
 - %APPDATA%/Roaming/anidbcli/session.json
 - ~/.anidbcli/session.json

**Comment by Jonybat** [comment]
That sounds good

**Comment by adameste** [comment]
Will try to implement it tomorrow, new version should be available by evening on PyPi.

**Comment by Jonybat** [comment]
Wow, no need to rush

**Comment by purposelycryptic** [comment]
>Well, I looked at the API specification again. The session times out after 35 minutes of not using it, so it's plenty of time. 

Wow, that's a *lot* longer than I thought it was - that definitely points a giant 100-foot finger to the frequent session initiations as the culprit. I just went by AniAdd's documentation and behavior (it times out after one minute of inactivity, then attempts a reconnect after five minutes), but the documentation I have for it is largely from 2013... I guess things changed just a bit since (which in retrospect, makes perfect sense).

Is there any way to have AnidbCLI terminate a session from its end once it's finished processing a command? I think I remember there being a call for it in the API, but not 100%. 

I realize this is effectively the opposite of @Jonybat's request, but I do have multiple downloads within a 35 minute window somewhat frequently (especially since the sessions would be chained, with the 35-minute timer restarting with each invocation of AnidbCLI), so if the sessions aren't being terminated at the end of the call, I can see myself getting banned on a daily basis :-/

Let me know if you want me to start a new issue for that, though, I know these things can get scrambled/chaotic pretty quickly

**Comment by Jonybat** [comment]
In fact, either implementation would work for me, I guess, as long as multiple logins (properly terminated) over a short period of time (under a minute) would not trigger a ban.

**Comment by adameste** [comment]
If you get logged in ince per 30 minutes you will probably not get banned. logging out certainly has no effect on not getting banned, so you might just let the session open or you could call the last invocation of anidbcli without the **-p** parameter, so the session would be closed normally.

**Comment by adameste** [comment]
Version 1.50 is live on PyPi with **-t** parameter as **-p** was already in use...
Solution was more complicated, because anidb check source session port/addres on udp socket. That means i have to bind the socket to the correct address manually when needed. That basically creates an udp server socket and triggers windows firewall popup. Didn't test it on linux, but it shouldnt be a problem. Let me know if it worked.

**Comment by Jonybat** [comment]
Awesome, I can confirm it fixed the issue for me. Thanks a lot, keep up the great work.

**Comment by adameste** [comment]
Perfect, quickstart updated, closing issue.
